import { collapsePath } from '../paths.js';
import type { CheatsheetResult } from './types.js';

export interface RenderOptions {
  /** Override the generation timestamp. Tests pin this for deterministic output. */
  generatedAt?: Date;
  /** Tuck version to include in frontmatter. */
  tuckVersion?: string;
  /**
   * Omit the `generated` timestamp from the output entirely. Use this when
   * the cheatsheet is committed and regenerated automatically (e.g. via a
   * `preSync` hook) — the wall-clock timestamp would otherwise produce a
   * 1-line `+/- generated:` diff on every sync regardless of whether
   * keybinds changed. Defaults to `false` (timestamp included).
   */
  includeTimestamp?: boolean;
}

/**
 * Escape characters that would break a GitHub-flavored markdown table
 * cell. Pipes need a backslash (otherwise the table splits); backticks
 * need literal-escape handling since we wrap cells in `code`. The
 * simplest robust approach: replace backticks with a visible surrogate
 * rather than escape them — almost no real keybind contains a literal
 * backtick, so this is safe.
 */
const escapeCell = (text: string): string =>
  text.replace(/`/g, "'").replace(/\|/g, '\\|').replace(/\n/g, ' ');

const collapseOrKeep = (p: string): string => {
  try {
    return collapsePath(p);
  } catch {
    return p;
  }
};

/**
 * Render a cheatsheet result as a markdown document.
 *
 * Layout:
 *   - YAML frontmatter with generation metadata (diff-friendly).
 *   - H1 title + summary line.
 *   - One H2 section per parser id, with a pipe table of entries.
 *   - Empty-result message when no sections produced entries.
 *
 * Source file annotations are included only for parsers that produce
 * entries from more than one file — for a single-file source (tmux's
 * `.tmux.conf`) the header already says where the entries come from,
 * so the per-row File column would be redundant.
 */
export const renderMarkdown = (
  result: CheatsheetResult,
  options: RenderOptions = {}
): string => {
  const includeTimestamp = options.includeTimestamp ?? true;
  const generatedAt = options.generatedAt ?? new Date();
  const iso = generatedAt.toISOString();
  const tuckVersion = options.tuckVersion ?? 'unknown';

  if (result.totalEntries === 0) {
    const frontmatter = [
      '---',
      ...(includeTimestamp ? [`generated: ${iso}`] : []),
      `tuckVersion: ${tuckVersion}`,
      'totalEntries: 0',
      '---',
    ];
    return [
      ...frontmatter,
      '',
      '# Dotfiles Cheatsheet',
      '',
      '_No keybinds detected in tracked files._',
      '',
      '_Supported sources: tmux, zsh, yazi. See `tuck cheatsheet --help` for details._',
      '',
    ].join('\n');
  }

  const lines: string[] = [];
  lines.push('---');
  if (includeTimestamp) lines.push(`generated: ${iso}`);
  lines.push(`tuckVersion: ${tuckVersion}`);
  lines.push(`totalEntries: ${result.totalEntries}`);
  lines.push(`sections: ${result.sections.length}`);
  lines.push('---');
  lines.push('');
  lines.push('# Dotfiles Cheatsheet');
  lines.push('');
  if (includeTimestamp) {
    lines.push(
      `_Generated by tuck on ${iso.slice(0, 10)} — do not edit by hand._  `
    );
  } else {
    lines.push('_Generated by tuck — do not edit by hand._  ');
  }
  lines.push(
    `_${result.totalEntries} entr${result.totalEntries === 1 ? 'y' : 'ies'} across ${result.sections.length} source${result.sections.length === 1 ? '' : 's'}._`
  );
  lines.push('');

  for (const section of result.sections) {
    const sourceFiles = new Set(section.entries.map((e) => e.sourceFile));
    const multiFile = sourceFiles.size > 1;

    const header =
      multiFile
        ? `## ${section.label}`
        : `## ${section.label} (${collapseOrKeep([...sourceFiles][0] ?? '')})`;
    lines.push(header);
    lines.push('');

    if (multiFile) {
      lines.push('| Keybind | Action | File |');
      lines.push('|---------|--------|------|');
      for (const entry of section.entries) {
        const loc = entry.sourceLine > 0
          ? `${collapseOrKeep(entry.sourceFile)}:${entry.sourceLine}`
          : collapseOrKeep(entry.sourceFile);
        lines.push(
          `| \`${escapeCell(entry.keybind)}\` | ${escapeCell(entry.action)} | \`${escapeCell(loc)}\` |`
        );
      }
    } else {
      lines.push('| Keybind | Action |');
      lines.push('|---------|--------|');
      for (const entry of section.entries) {
        lines.push(
          `| \`${escapeCell(entry.keybind)}\` | ${escapeCell(entry.action)} |`
        );
      }
    }
    lines.push('');
  }

  return lines.join('\n');
};

/**
 * Render a cheatsheet result as JSON.
 *
 * Shape is optimized for jq/fzf consumers: entries are flattened across
 * sections with `parserId` attached to each row, so piping through
 * `jq -r '.entries[] | [.keybind, .action] | @tsv'` into fzf is a
 * one-liner. Optional fields (`category`, `section`) are emitted as
 * explicit `null` rather than omitted keys so `select(.category == null)`
 * works without defensive `// empty` gymnastics.
 *
 * `sections` is retained as a summary array (parserId + label +
 * entryCount) for consumers that want section-level counts without
 * re-grouping the flat list.
 */
export const renderJson = (
  result: CheatsheetResult,
  options: RenderOptions = {}
): string => {
  const includeTimestamp = options.includeTimestamp ?? true;
  const tuckVersion = options.tuckVersion ?? 'unknown';

  const entries = result.sections.flatMap((section) =>
    section.entries.map((entry) => ({
      parserId: section.parserId,
      keybind: entry.keybind,
      action: entry.action,
      sourceFile: entry.sourceFile,
      sourceLine: entry.sourceLine,
      category: entry.category ?? null,
      section: entry.section ?? null,
    }))
  );

  // The `generated` field is omitted entirely when includeTimestamp is
  // false — not emitted as null. Consumers that want a "missing or
  // present" check can use `select(.generated)`; the alternative (always
  // emit, sometimes null) muddies the contract.
  const payload = {
    ...(includeTimestamp && {
      generated: (options.generatedAt ?? new Date()).toISOString(),
    }),
    tuckVersion,
    totalEntries: result.totalEntries,
    entries,
    sections: result.sections.map((s) => ({
      parserId: s.parserId,
      label: s.label,
      entryCount: s.entries.length,
    })),
    skippedParsers: result.skippedParsers,
  };

  return `${JSON.stringify(payload, null, 2)}\n`;
};
